; PlatformIO Project Configuration File
;
; ESP32-DEVKITC-VIE + VS1838B(受信) + SGN119(送信) 赤外線学習リモコン
;
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.5
